### ISSUE TITLE
[Request] A darker theme which match Tomorrow Colorscheme

### ISSUE THREAD

**Issue by babygau** [oivva/boxy#24] opened 2016-03-06 12:10 UTC
Hi @oivva,

Thank you for great theme. As you can see from the title, could you pls add another theme which match Tomorrow's color? The current dark version #2 is great but it is still low contrast for me.

Many thanks!

**Comment by oivva** [comment] 2016-03-07 03:42
Hi @babygau,

Thanks for your request. Unfortunately I have no plans to add more themes, but I'm open to add new options to existing ones. Can you explain me how should it look like?

**Comment by babygau** [comment] 2016-03-08 11:14
@oivva,

Thank you for your response. Could you please take reference from this **Cyanide Theme**. By saying `darker` color, I meant `black` color actually. Please look at sidebar, tabs, and panel, they all match with `black` color.

I'm really looking forward to it! Many thanks in advance

![image](https://cloud.githubusercontent.com/assets/1514823/13600055/8b3d1fd0-e57a-11e5-8163-3b1d9b5088dd.png)

**Comment by oivva** [comment] 2016-06-01 16:54
I'll add darker version in the 2.1.0 version. You will need to use next options:
```js
"theme": "Boxy Tomorrow.sublime-theme",
"theme_darker": true,
```
As for now I close this issue as duplicate of #25.

**Closed by oivva** 2016-06-01 16:54 UTC
Labels: duplicate
